Add and fix a bunch of AI ranges and some point visualizations
Cosine256/spelunky-2-ai-visualizer pull request #1
Opened 2024-12-15 05:07 UTC by jaythebusinessgoose

Adds ranges for:
- Chatters chatting (Caveman/Tiki Man/Witch Doctor)
- Grubs turning to flies
- Giant spider small jump
- Leprachaun "special jump"
- Mole activate
- Necromancer resurrection
- Pangxie claw retraction
- Quillback stomp
- UFO rise/lower/stop rising
- Witch doctor skull's orbit

Fixes ranges for:
- Giant spider
- Hermit crab emerging when in a cubby
- Hundun moving right in non-standard level width
- Lavamander aggro
- Mech's rider entity type filter
- Mole emerge when trapped
- Removed olmite jump range while mounted in a mech
- Hid some quillback ranges while not active
- Spider aggro is actually a clipped circle
- Active/visible conditions in witch doctor ranges
- Active part of yeti king's freeze hurtbox
- Yeti king/queen ranges now calculate their hitboxes instead of hardcoding them

Added point checks for:
- Flying fish flying up into a tile
- Olmites in corridors
- Lavamander "am I in lava?" checks

Answered some questions in TODO comments

2025-03-19 05:40 UTC, Cosine256 requested changes
I've commented on a few changes that seemed wrong or unclear. Thank you for doing this though. It's great to have a bunch of these updated based on the actual code. Stuff like the UFO and mole were difficult to test manually, and I didn't even know about things like the hermit crab cubby behavior.

2025-03-19 05:40 UTC, Cosine256 commented on ai/giant_spider.lua
> +            shape = geometry.create_circle_shape(7):clip_box(-0.95, nil, 0.95, 0),
I'm not observing this behavior as a circular range in testing. The spider drops when I'm less than 7 below it no matter where I am within the horizontal range, as though it were a box range.

2025-03-19 05:40 UTC, Cosine256 commented on ai/giant_spider.lua
> +            -- TODO: Width is controlled by trigger_distance field, which defaults to 0.95 for this entity type.
Irrelevant comment copied from other range.

2025-03-19 05:40 UTC, Cosine256 commented on ai/hermit_crab.lua
> +        local right = get_entities_at(0, MASK.ACTIVEFLOOR | MASK.FLOOR, entx + 1, enty, entlayer, 0.5)
This doesn't seem right. It's triggering cubby range visualizations near non-solid floors like `FLOOR_CLIMBING_POLE`, but the hermit crabs are emerging based on the normal range.

2025-03-19 05:40 UTC, Cosine256 commented on ai/lavamander.lua
> +            shape = geometry.create_circle_shape(8):clip_box(nil, -1, nil, 4),
I'm not observing the behavior changes you made here. It still seems to have a distinct aggro range that lets it target a player, and then an infinitely wide rise-and-attack for as long as the target hasn't been lost.

2025-03-19 05:40 UTC, Cosine256 commented on ai/leprechaun.lua
> +            -- Range in which the leprechaun can jump if there is a tile above an empty space 2 in front of it.
I don't really understand what behavior this range indicates. I see leprechauns just jump randomly and frequently unless the player is in the "no jump" range, in which case I never see them jump at all.

2025-03-19 05:40 UTC, Cosine256 commented on ai/mech.lua
> +                and ent.gun_cooldown == 0 and (rider.type.id >= ENT_TYPE.MONS_PET_TUTORIAL and rider.type.id <= ENT_TYPE.MONS_CRITTERSLIME)
This is upsetting, but I suppose I'm not surprised they'd code it that way, so we'll honor their spaghetti code in this mod too.

2025-03-19 05:40 UTC, Cosine256 commented on ai/mole.lua
> +            label = "Active"
Should be "Activate"?

2025-03-19 05:40 UTC, Cosine256 commented on ai/olmite.lua
> +                return geometry.create_point_set_shape(Vec2:new(ctx.offsetx - ctx.hitboxx, 1), Vec2:new(ctx.offsetx + ctx.hitboxx, 1))
Was preprocessing needed for this, since you could just check these fields directly in `ent` instead of using `ctx`?

2025-03-19 05:40 UTC, Cosine256 commented on ai/pangxie.lua
> +        { -- Claw Retract
What are these retract ranges meant to represent? I'm not sure what behavior is changing or what entity is being checked for.

2025-03-19 05:40 UTC, Cosine256 commented on ai/quillback.lua
> +                return ent.move_state == 2
The stomp behavior still seems to be active in the attacking state (6) before he rolls, not just the jumping state.

2025-03-19 05:40 UTC, Cosine256 commented on ai/spider.lua
> +            shape = geometry.create_circle_shape(7):clip_box(-0.4, nil, 0.4, 0),
Same comment as giant spider: I'm still seeing behavior that looks like a box, not a clipped circle.

2025-03-19 05:40 UTC, Cosine256 commented on ai/yeti_queen.lua
> +                -- ANSWER: Does it make sense to make it "active" during move_state 7 (the wind-up for the punch)?
I feel like hurtboxes should only appear active during frames that they can hurt or apply their effect.

2025-05-18 05:00 UTC, jaythebusinessgoose commented on ai/giant_spider.lua
> +            shape = geometry.create_circle_shape(7):clip_box(-0.95, nil, 0.95, 0),
You're right. I finally figured out what was going on, they're comparing to y^2 >= 49 so I thought it was (x^2 + y^2)

2025-05-18 05:00 UTC, jaythebusinessgoose commented on ai/hermit_crab.lua
> +        local right = get_entities_at(0, MASK.ACTIVEFLOOR | MASK.FLOOR, entx + 1, enty, entlayer, 0.5)
Added in solid flag check.

2025-05-18 05:00 UTC, jaythebusinessgoose commented on ai/leprechaun.lua
> +            -- Range in which the leprechaun can jump if there is a tile above an empty space 2 in front of it.
There are some explanations and screenshots in [this doc](https://docs.google.com/spreadsheets/d/1rk_ykderb6AWjlhVCHecDKCekkqhadiLuooirSq1l1w/edit?gid=1417293922#gid=1417293922) that might clear this up. Leprechauns and cats have special jumps in this behavior.

2025-05-18 05:00 UTC, jaythebusinessgoose commented on ai/mech.lua
> +                and ent.gun_cooldown == 0 and (rider.type.id >= ENT_TYPE.MONS_PET_TUTORIAL and rider.type.id <= ENT_TYPE.MONS_CRITTERSLIME)
Yeah, I figured if people are combining this with their mods which allow other entities to ride mechs, we might as well keep things accurate to what would happen in that scenario.

2025-05-18 05:00 UTC, jaythebusinessgoose commented on ai/olmite.lua
> +                return geometry.create_point_set_shape(Vec2:new(ctx.offsetx - ctx.hitboxx, 1), Vec2:new(ctx.offsetx + ctx.hitboxx, 1))
I think I was trying to do something else in the preprocessing at first, not needed anymore.

2025-05-18 05:00 UTC, jaythebusinessgoose commented on ai/pangxie.lua
> +        { -- Claw Retract
It is the claw entity itself that needs to be in one of these ranges. If the claw never comes to rest or enters one of these ranges, it will remain out forever.

2025-05-18 05:00 UTC, jaythebusinessgoose commented on ai/quillback.lua
> +                return ent.move_state == 2
The new logic should be more accurate.

2025-05-18 05:00 UTC, jaythebusinessgoose commented on ai/yeti_queen.lua
> +                -- ANSWER: Does it make sense to make it "active" during move_state 7 (the wind-up for the punch)?
Yeah that makes sense, it just seems so weird with it being just a frame of active state.

2025-08-01 06:49 UTC, Cosine256 approved these changes
Looks good, thanks for adding these. I will clean up `TODO` and `ANSWER` comments, and maybe tweak some of the labels.

2025-08-01 06:51 UTC, merged